name: "Asana Writers — Analyze Only"

on:
  workflow_dispatch:
    inputs:
      jsonl_path:
        description: "Optional path to a JSONL file (in repo) to analyze (e.g., data/asana_writer_tasks_sample.jsonl)"
        required: false
        default: ""

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agents/asana-writers

    env:
      PIP_NO_CACHE_DIR: "1"
      PIP_DISABLE_PIP_VERSION_CHECK: "1"
      PIP_ROOT_USER_ACTION: "ignore"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (fresh, force correct OpenAI SDK)
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          # Install your repo deps first
          pip install --no-cache-dir -r requirements.txt || true
          # Hard-pin SDKs we rely on (force reinstall to avoid stale envs)
          pip install --no-cache-dir --upgrade --force-reinstall "httpx<0.28" "openai>=1.51.0"
          # Sanity print
          python -c 'import sys, openai; from openai import OpenAI; c=OpenAI(); print("python:", sys.version); print("openai:", openai.__version__); print("Has responses?", hasattr(c, "responses"))'

      - name: Write service account key
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          printf '%s' "$SERVICE_ACCOUNT_JSON" > service_account.json

      - name: Show candidate JSONL files (debug)
        run: |
          ls -la
          ls -la *.jsonl || true
          ls -la data || true
          ls -la output || true
          test -f prompt.txt && echo "Found prompt.txt" || echo "prompt.txt missing"
          test -f rules.json && echo "Found rules.json" || echo "rules.json missing"

      - name: Run analyzer
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ASANA_GOOGLE_SHEET_ID: ${{ secrets.ASANA_GOOGLE_SHEET_ID }}
          ANALYZE_JSONL_PATH: ${{ github.event.inputs.jsonl_path }}
          OPENAI_MODEL: gpt-4.1-mini     # or gpt-4o-mini / gpt-4.1
          WRITER_CAPACITY_JSON: |
            {"Dalton Phillips":1200,"Julia Pizzuto":1200,"Michaela Leung":1200,
             "Germaine Foo":1200,"Rachel Taylor-Northam":1200,"Lexa Garian":1200,"Bethany Osborn":1200}
          INCLUDE_HUB_PARENTS: "false"
          PROMPT_PATH: agents/asana-writers/prompt.txt
          RULES_JSON_PATH: agents/asana-writers/rules.json
        run: |
          source .venv/bin/activate
          python analyze_workload.py

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asana-writer-analysis
          path: |
            agents/asana-writers/assistant_narrative_*.txt
            agents/asana-writers/*_upload.json
