name: Asana Writers — Analyze Only

on:
  workflow_dispatch:
    inputs:
      jsonl_path:
        description: "Optional path to a JSONL file to analyze"
        required: false
        default: "data/asana_writer_tasks_sample.jsonl"

jobs:
  analyze:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agents/asana-writers
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt

      - name: Write service account key
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          printf '%s' "$SERVICE_ACCOUNT_JSON" > service_account.json

      - name: Classify tasks
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_CLASSIFIER_ID: ${{ secrets.OPENAI_CLASSIFIER_ID }}
          ANALYZE_JSONL_PATH: ${{ github.event.inputs.jsonl_path }}
        run: |
          source .venv/bin/activate
          python classify_tasks.py

      - name: Upload debug/artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asana-writer-debug
          path: |
            agents/asana-writers/output/*.txt
            agents/asana-writers/*.json
            agents/asana-writers/*_upload.json


      - name: Summarize workload
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_SUMMARIZER_ID: ${{ secrets.OPENAI_SUMMARIZER_ID }}
          ASANA_GOOGLE_SHEET_ID: ${{ secrets.ASANA_GOOGLE_SHEET_ID }}
          # Optional: {"Name": minutes, ...}
          CAPACITY_JSON: '{"Dalton Phillips":1200,"Julia Pizzuto":1200,"Michaela Leung":1200,"Germaine Foo":1200,"Rachel Taylor-Northam":1200,"Lexa Garian":1200,"Bethany Osborn":1200}'
        run: |
          source .venv/bin/activate
          python summarize_workload.py

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asana-writer-outputs
          path: agents/asana-writers/output/*
