name: Asana Writers Pull

on:
  workflow_dispatch:        # Manual run
  schedule:
    - cron: "0 21 * * 5"    # Fridays 21:00 UTC (~5pm ET during DST, ~4pm ET standard)

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: agents/asana-writers

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
          # Ensure OpenAI + httpx compatibility in case requirements.txt gets edited later
          pip install "httpx<0.28" "openai==1.40.2"

      - name: Write service account key
        env:
          SERVICE_ACCOUNT_JSON: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        run: |
          # Use printf to avoid stray newlines/indentation
          printf '%s' "$SERVICE_ACCOUNT_JSON" > service_account.json

      # --- Pull tasks into Sheet + write JSONL locally ---
      - name: Run pull
        env:
          ASANA_TOKEN: ${{ secrets.ASANA_TOKEN }}
          ASANA_WORKSPACE_GID: ${{ secrets.ASANA_WORKSPACE_GID }}
          ASANA_GOOGLE_SHEET_ID: ${{ secrets.ASANA_GOOGLE_SHEET_ID }}
        run: |
          source .venv/bin/activate
          python asana_pull.py

      - name: Upload JSONL artifact
        uses: actions/upload-artifact@v4
        with:
          name: asana-writer-jsonl
          path: agents/asana-writers/*.jsonl

      # --- Analyze + write Slack-style narrative into the Sheet ---
      - name: Analyze workload with Assistant
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_ASSISTANT_ID: ${{ secrets.OPENAI_ASSISTANT_ID }}
          ASANA_GOOGLE_SHEET_ID: ${{ secrets.ASANA_GOOGLE_SHEET_ID }}
        run: |
          source .venv/bin/activate
          python analyze_workload.py

      - name: Upload analysis artifacts
        uses: actions/upload-artifact@v4
        with:
          name: asana-writer-analysis
          path: |
            agents/asana-writers/assistant_narrative_*.txt
            agents/asana-writers/*_upload.json
